### PR TITLE
[OSL-2017] fix for asset images

### PR DESCRIPTION
**Pull request by steinim**
I don't know if this is the best solution for fixing the problem with dynamic filenames for different sizes of images. Please let me know if it should be dealt with in some other way.

### CODE REVIEW

**Comment by mattstratton** [comment]
Can you explain a bit more of what you're trying to do? We actually do solve for this problem in the site now - in the master build we set srcset and create the various sizes; the problem is that we are only setting them properly for image types we know about.

Take a look at this `gulp` task to get some ideas on what we do in asset pipelining when releasing to production:

https://github.com/devopsdays/devopsdays-web/blob/master/gulp/tasks/responsive-images.js

**Comment by mattstratton** [comment]
Specifically look at this line:

https://github.com/devopsdays/devopsdays-web/blob/master/gulp/tasks/responsive-images.js#L123

You can see that we set the different images for non-specific images to 100%; there might be a way that we can create some kind of element you can specify (or more to the fact, have a specific directory in your `static` directory that lets us process your images better).

**Comment by mattstratton** [comment]
I've added an idea to our roadmap to start thinking about this - take a look at this one and upvote it if it seems like what you have in mind https://portal.prodpad.com/24442/ideas/361732

**Comment by steinim** [comment]
Looks like png and jpeg doesn't work as expected. Switching to jpg seems to fix the issues.

**Comment by steinim** [comment]
I'll push a pull request for devopsdays-web with the changes, so can you please merge this one as they depend on each other.

**Pull request merged**
